version: '3'

volumes:
  data:
  redis:

services:

  nginx:
    image: nginx:1.13.3-alpine
    links:
      - api
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/log/nginx
      - /var/run
    volumes:
      - ./nginx.snippets:/etc/nginx/snippets:ro
      - ./nginx.sites:/etc/nginx/sites-enabled:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - /var/www:/var/www
    ports:
      - '80:80'
      - '443:443'

  db:
    image: postgres:9.6.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=xxx
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.1-alpine
    restart: always
    read_only: true
    volumes:
      - redis:/data

  api:
    image: api
    read_only: true
    restart: always
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NODE_DEBUG=false
      - WEBSITE_URL=https://example.com
      - FRONTEND_HOST_WHITELIST=localhost
      - DATABASE_URL=postgres://user:xxx@db:5432/api
      - DATABASE_DEBUG=false
      - REDIS_URL=redis://redis:6379/1
      - SESSION_SECRET=xxx
      - FACEBOOK_ID=xxx
      - FACEBOOK_SECRET=xxx
      - GOOGLE_ID=xxx
      - GOOGLE_SECRET=xxx
      - TWITTER_KEY=xxx
      - TWITTER_SECRET=xxx
    expose:
      - '3000'
    # ports:
    #   - '0.0.0.0:9229:9229' # V8 inspector
